# Generated by Django 4.2.4 on 2024-02-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0003_delete_installer_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customuser_ptr',
        ),
        migrations.DeleteModel(
            name='Installer',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
