# Generated by Django 4.2.4 on 2024-02-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0005_installer_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='installer_profile',
        ),
        migrations.DeleteModel(
            name='Installer',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
