# Generated by Django 4.2.4 on 2024-02-12 23:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0006_remove_userprofile_customuser_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('installed_assets', models.IntegerField(default=0)),
                ('installer_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tariff', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('solarapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tariff', models.FloatField(blank=True, null=True)),
                ('conventional_pricing', models.FloatField(blank=True, null=True)),
                ('ai_dynamic_pricing', models.FloatField(blank=True, null=True)),
                ('installer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles_installer', to='solarapp.installer')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('solarapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SolarSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential_shading', models.BooleanField(default=False)),
                ('solar_panel_type', models.CharField(blank=True, max_length=100)),
                ('solar_size_watts', models.IntegerField(default=0)),
                ('efficiency_ratings', models.IntegerField(default=0)),
                ('total_number_of_panels', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_specifications', to='solarapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InverterSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_size', models.FloatField(default=0)),
                ('efficiency', models.FloatField(default=0)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('voltage_input_range', models.FloatField(default=0)),
                ('mppt_channels', models.CharField(blank=True, max_length=100)),
                ('grid_type', models.CharField(blank=True, max_length=100)),
                ('communication_features', models.CharField(blank=True, max_length=200)),
                ('protection_features', models.CharField(blank=True, max_length=200)),
                ('certifications', models.CharField(blank=True, max_length=200)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverter_specifications', to='solarapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('load_watts', models.FloatField(default=0)),
                ('load_kw', models.FloatField(default=0)),
                ('generation', models.FloatField(default=0)),
                ('tariff', models.FloatField(default=0)),
                ('charge', models.FloatField(default=0)),
                ('dynamic_tariff', models.CharField(blank=True, max_length=200)),
                ('dynamic_charge', models.FloatField(default=0)),
                ('wasted_energy', models.FloatField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_consumption_data', to='solarapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryStorageSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity_kwh', models.FloatField(default=0)),
                ('usable_capacity_kwh', models.FloatField(default=0)),
                ('type_of_battery', models.CharField(blank=True, max_length=100)),
                ('voltage_v', models.FloatField(default=0)),
                ('depth_of_discharge', models.FloatField(default=0)),
                ('cycle_life', models.IntegerField(default=0)),
                ('charge_discharge_rate', models.FloatField(default=0)),
                ('efficiency', models.FloatField(default=0)),
                ('management_system', models.CharField(blank=True, max_length=200)),
                ('warranty_and_lifespan', models.CharField(blank=True, max_length=200)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_storage_specifications', to='solarapp.userprofile')),
            ],
        ),
    ]
