# Generated by Django 4.2.4 on 2024-02-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0007_installer_userprofile_solarspecification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='address_found',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installer',
            name='address_provided',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_found',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_provided',
            field=models.CharField(blank=True, null=True),
        ),
    ]
