# Generated by Django 4.2.4 on 2024-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0008_installer_address_found_installer_address_provided_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='address_found',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='address_provided',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='installer',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_found',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_provided',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_found',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_provided',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_names',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installer',
            name='company_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installer',
            name='contact_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
