# Generated by Django 4.2.4 on 2024-02-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0009_remove_installer_address_found_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
